### PR TITLE
fixed some examples

### PR DESCRIPTION
**Pull request by katopz**

### CODE REVIEW

**Comment by JMLX42** [comment]
Hello,

1) The distortion is perfectly logical. Constraining the size of the stage/viewport is not a practical solution (meaning it doesn't fit any real life application). It's just a workaround to hide the "issue". It's a deceptive trick. Therefore, it should not be used/encouraged.

2) and 3) are cosmetic arrangements and they are very subjective. You must not call addCube() or addTeapot() at every frame: the goal of those samples is to "benchmark" how many objects can be added until the fps drop below 30.

Regards,

**Comment by katopz** [comment]
oh! for 2 and 3 i just realize what going on there, for some reason Monitor.monitor.framerate always return 0 there
so addCube via enterFrameHandler never call then it show nothing there (so i have to call addCube via initializeScene instead)

do i've to do anything to get Monitor.monitor.framerate working?

Thanks!

**Comment by JMLX42** [comment]
That's just weird. Are you sure the Monitor is on the Stage?

**Comment by katopz** [comment]
after searching whole package, seem like it's not
i need to add

``` as3
addChild(Monitor.monitor);
```

via MinkoExampleApplication in initialize function to make it work

**Pull request closed without merging**
