### PR TITLE
Simple water simulation demo.

### PR DESCRIPTION
**Pull request by sindney**
Pull request in dev branch ;)

### CODE REVIEW

**Comment by JMLX42** [comment]
Hello and thank you for your contribution!

There are several things that makes it impossible for us to merge this pull request:
- the XZPanel class is a duplicate of QuadGeometry
- some of your shader properties are duplicate from the standard/phong/env. mapping properties (such as "timer" or "environment map")
- your code does not use the latest version of the dev branch (Viewport init. is different, streams have to be locked before being modified for acceptable performances)
- the coding style does not fit our coding style (egyptian style brackets, missing spaces around the colon operator...)

I will help you updating your code so it fits the coding style in this thread in case you need any help:

http://answers.aerys.in/discussion/246/using-sampletexture-in-vertex-shader

I'm deeply sorry but things have to be as consistent as possible for the sake of the entire community.
Thank you for your understanding :)

**Comment by sindney** [comment]
I understand, don't feel sorry, it's ok, keep up your good work :D

2012/12/13 Jean-Marc Le Roux notifications@github.com

**Comment by sindney** [comment]
Oh, right, about QuadGeometry, i think a "type" option should be added.
which indicates the align of the quad, XZ,XY,YZ ...

2012/12/13 Xin Hou sindneymail@gmail.com

**Comment by JMLX42** [comment]
But you can also rotate the quad using the transform property of the Mesh :)

**Pull request closed without merging**
